name: .NET Core

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore **/*.csproj

    - name: Build
      run: dotnet build **/*.csproj --no-restore

    - name: Custom script
      run: echo "Custom script execution"

  other-action:
    runs-on: ubuntu-latest
    steps:
    - name: Other action
      run: echo "Other action execution"
